site_name: CPM library
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - bash
    - yaml
    - json
    - markdown
    - makefile

extra_css:
  - style.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      enable_inventory: false
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          load_external_modules: true
          options:
            show_source: false
            docstring_style: numpy
            docstring_section_style: table
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
  - mkdocs-jupyter:
            no_input: False
            include_source: True
            ignore: ['examples/bandit.py']

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Troubleshooting: troubleshooting.md
      - Roadmap: roadmap.md
  - Examples:
      - examples/associative-learning.ipynb
      - examples/bandit-task.ipynb
      - examples/metacognition.ipynb
      - examples/model-parameter-recovery.ipynb
      - examples/model-recovery.ipynb
      - examples/fitting-hierarchical-estimation.ipynb
      - examples/fitting-hierarchical.ipynb
  - API Reference:
      - cpm.generators: api/generators.md
      - cpm.models: api/models.md
      - cpm.optimisation: api/optimisation.md
      - cpm.hierarchical: api/hierarchical.md
      - cpm.applications: api/applications.md
      - cpm.utils: api/utils.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true