site_name: CPM library
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - bash
    - yaml
    - json
    - markdown
    - makefile

extra_css:
  - style.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      enable_inventory: false
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          import:
            - https://docs.python-requests.org/en/master/objects.inv
          load_external_modules: true
          options:
            show_source: false
            docstring_style: numpy
            docstring_section_style: table
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
  - mkdocs-jupyter:
            no_input: False
            include_source: True
            ignore: ['examples/bandit.py']



markdown_extensions:
  # - markdown_include.include:
  #     base_path: .
  - admonition
  - pymdownx.arithmatex
